blank_issues_enabled: false
contact_links:
  - name: FAQ
    url: https://pizzaparty.menu/faq
    about: Check our FAQ before asking a question
  - name: Contact us
    url: https://pizzaparty.menu/contact
    about: Contact us privately